type: "site"
src: './input'

#-----SITE SPECIFIC PARAMETERS-----#
licel_parameters:
  spatial_resolution: 7.5 # spatial resolution in m
  volt_resolution: 50 # LICEL voltage resolution in mV
  bit_resolution: 16 # LICEL ADC resolution in bits
  n_bins: 4096 # number of bins per sample

bias_correction_window: 500 #Bias correction window in bins

dt1: 4e-3 # Dead time for ch1 (532 co-pol near)
dt2: 4e-3 # Dead time for ch2 (532 cross-pol)
nb: 4096  # number of bins
zb1: -5   # zero bin position for ch1 (analog)
zb2: -5   # zero bin position for ch2 (analog)
psrat: 1.02e0    # P/S ratio for ch1-ch2 (photon)
filename_prefix: "h" #prefix for the file name

use_darkcurrent: True #use dark current file for noise correction
darkcurrent: "" #dark current path
channel: "BT3_L1" #channel to plot