type: "global"
path: 
      dest: "./export"  #dest path of exported files
      
site: "COR" 
#-----SITE NAME-----#
#locations:
#"COR"
#"TUC""
#"VM"
#"SMN"
#"NQN"
#"BAR"
#"TRW"
#"COM"
#"OAPA"
delta_day: 3   #numbr of day to plot
max_height: 20  #maximum data height (km)
plot_last_days: False #plot mode: "dates(False)" or "last days(True)"
days_to_plot: 3 #number of last days to plot
starting_date: "2025-04-23" #dates to plot: "YYYY-MM-DD"
end_date: "2025-04-27"

#-----PLOT PARAMETERS-----#
plot_limits:
      z_min: -350
      z_max: 700
      h_max: 10 #maximum plot height (km)
use_log: False #use log scale for the plot
auto_scale: True #auto scale the plot limits





