type: "global"
path: 
      dest: "./export"  #dest path of exported files

site: "COR" 
#-----SITE NAME-----#
#locations:
#"COR"
#"TUC""
#"VM"
#"SMN"
#"NQN"
#"BAR"
#"TRW"
#"COM"
#"OAPA"
delta_day: 3   #numbr of day to plot
max_height: 20  #maximum plot height (km)
plot mode: "last days" #plot mode: "dates" or "last days"
days_to_plot: 3 #number of last days to plot
starting_date: "2023-10-01" #dates to plot: "YYYY-MM-DD"
end_date: "2023-10-02"
# Promedio temporal: ver datos cada x cantidad de tiempo. Que no se rompa por promediar mas o menos.
# Tamaño de la ventana
# Offset de altura
# Ventana del offset de bias
# Dia máximo y dia mínimo
# Ruta corriente oscura 
# Nombre de la señal que se va a graficar




