type: "site"
src: './input'

#-----SITE SPECIFIC PARAMETERS-----#
#dsp parameters
bias_correction_window: 500 #Bias correction window in bins
spatial_avg_h: 4 #Spatial average height in bins
time_avg: 15 #Time average in minutes

#site parameters
channel: "BT3_L1" #channel to plot
zb1: -5   # zero bin position for ch1 (analog)
zb2: -5   # zero bin position for ch2 (analog)
psrat: 1.02e0    # P/S ratio for ch1-ch2 (photon)
filename_prefix: "h" #prefix for the file name

#dark current parameters
use_darkcurrent: True #use dark current file for noise correction
darkcurrent: "" #dark current path
